#!/usr/bin/env python3
"""Generate paper_ca/scaling_data.tex from aggregated metrics.

Identical to paper_asym_consequence/scripts/make_scaling_table.py but writes
into paper_ca/ — Arka's canonical Overleaf source.

NEW (claude, 2026-04-29) — Arka please tweak formatting freely.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path("/home/paperspace/aysm")
OUT = Path("/home/paperspace/aysm/paper_ca/scaling_data.tex")

CELL = json.loads((ROOT / "exp22_paper_full_rubrics/eval/cell_metrics.json").read_text())
QQ = json.loads((ROOT / "exp21_scaling/result_analysis/metrics_v6.json").read_text())
QQUAL = json.loads((ROOT / "exp21b_scaling_qualitative/result_analysis/metrics_qualitative.json").read_text())
_SF_PATH = ROOT / "qq_result" / "size_family" / "swe_size_family_metrics.json"
SF_SWE = json.loads(_SF_PATH.read_text()) if _SF_PATH.exists() else {}

QWEN_KEY = {"qwen9b": "qwen-9b", "qwen122b": "qwen-122b", "qwen397b": "qwen-397b"}
QT = {"t1": "+1_0_-1", "t5": "+1_0_-5", "t10": "+1_0_-10"}
QQL = {"qual_p1": "p1_catastrophic", "qual_p2": "p2_fired", "qual_p3": "p3_nuclear"}

FAMS = [
    ("gemini_lite",  "Gemini Flash-Lite"),
    ("gemini_flash", "Gemini Flash"),
    ("gemini_pro",   "Gemini Pro"),
    ("qwen9b",       "Qwen 9B"),
    ("qwen122b",     "Qwen 122B-A10B"),
    ("qwen397b",     "Qwen 397B-A17B"),
]

QUANT_RIDS = ["t1", "t5", "t10"]
QUAL_RIDS = ["qual_p1", "qual_p2", "qual_p3"]
SWE_QUAL_RIDS = ["qual_q1", "qual_q2", "qual_q3"]


def get(bench: str, fam: str, rid: str):
    if bench == "swe":
        v = SF_SWE.get(f"swe__{fam}__{rid}")
        if v:
            return v
    v = CELL.get(f"{bench}__{fam}__{rid}")
    if v:
        return v
    if bench == "math" and fam in QWEN_KEY:
        if rid in QT:
            return QQ.get(QWEN_KEY[fam], {}).get("thinking", {}).get(QT[rid])
        if rid in QQL:
            return QQUAL.get(QWEN_KEY[fam], {}).get(QQL[rid])
    return None


def fmt(d, key):
    if not d:
        return "--"
    v = d.get(key)
    if v is None:
        return "--"
    if isinstance(v, float):
        return f"{v:.1f}"
    return str(v)


def row(famkey, label):
    cells = [label]
    for rid in QUANT_RIDS:
        d = get("math", famkey, rid)
        cells.append(fmt(d, "base_acc_pct"))
        cells.append(fmt(d, "abst_rate_pct"))
    for rid in QUAL_RIDS:
        d = get("math", famkey, rid)
        cells.append(fmt(d, "base_acc_pct"))
        cells.append(fmt(d, "abst_rate_pct"))
    for rid in QUANT_RIDS:
        d = get("swe", famkey, rid)
        cells.append(fmt(d, "base_acc_pct"))
        cells.append(fmt(d, "abst_rate_pct"))
    for rid in SWE_QUAL_RIDS:
        d = get("swe", famkey, rid)
        cells.append(fmt(d, "base_acc_pct"))
        cells.append(fmt(d, "abst_rate_pct"))
    return " & ".join(cells) + r" \\"


LATEX = []
LATEX.append(r"% NEW (claude, 2026-04-29) — Arka please edit/discard freely.")
LATEX.append(r"% Auto-generated by paper_ca/scripts/make_scaling_table.py")
LATEX.append(r"% Cells with `--' are not yet graded (size_family SWE eval pending).")
LATEX.append(r"")
LATEX.append(r"\begin{table}[t]")
LATEX.append(r"  \centering")
LATEX.append(r"  \footnotesize")
LATEX.append(r"  \setlength{\tabcolsep}{3pt}")
LATEX.append(r"  \caption{Effect of scale on consequence-aware behavior. Each cell shows \emph{base accuracy} (\%) and \emph{abstention rate} (\%). Quant rubrics use the symmetric $+1/0/-X$ form (cf.~\cref{sec:quantitative}); qual prompts are p1 catastrophic / p2 fired / p3 nuclear (math) and q1 catastrophic / q2 fired / q3 nuclear (SWE). Within each model family, both metrics are essentially flat across scale. SWE columns marked `--' are pending grading.}")
LATEX.append(r"  \label{tab:scaling}")
LATEX.append(r"  \begin{tabular}{l|cc cc cc|cc cc cc|cc cc cc|cc cc cc}")
LATEX.append(r"    \toprule")
LATEX.append(r"     & \multicolumn{6}{c|}{Math quant} & \multicolumn{6}{c|}{Math qual} & \multicolumn{6}{c|}{SWE quant} & \multicolumn{6}{c}{SWE qual} \\")
LATEX.append(r"     & \multicolumn{2}{c}{t1} & \multicolumn{2}{c}{t5} & \multicolumn{2}{c|}{t10}"
              r" & \multicolumn{2}{c}{p1} & \multicolumn{2}{c}{p2} & \multicolumn{2}{c|}{p3}"
              r" & \multicolumn{2}{c}{t1} & \multicolumn{2}{c}{t5} & \multicolumn{2}{c|}{t10}"
              r" & \multicolumn{2}{c}{q1} & \multicolumn{2}{c}{q2} & \multicolumn{2}{c}{q3} \\")
LATEX.append(r"    Family & acc & abs & acc & abs & acc & abs"
              r" & acc & abs & acc & abs & acc & abs"
              r" & acc & abs & acc & abs & acc & abs"
              r" & acc & abs & acc & abs & acc & abs \\")
LATEX.append(r"    \midrule")
LATEX.append(r"    \multicolumn{25}{l}{\emph{Gemini family}} \\")
for k, lab in FAMS[:3]:
    LATEX.append("    " + row(k, lab))
LATEX.append(r"    \midrule")
LATEX.append(r"    \multicolumn{25}{l}{\emph{Qwen family}} \\")
for k, lab in FAMS[3:]:
    LATEX.append("    " + row(k, lab))
LATEX.append(r"    \bottomrule")
LATEX.append(r"  \end{tabular}")
LATEX.append(r"\end{table}")
LATEX.append(r"")

OUT.write_text("\n".join(LATEX) + "\n")
print(f"wrote {OUT}")
